name: ml_Ali
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  - scikit-learn
  - psutil
  - pyyaml
  - requests
  - tqdm
  - pillow
  - jinja2
  - joblib
  - packaging
  - setuptools
  - wheel

  - pip:
      - accelerate==1.12.0
      - hf-xet==1.2.0
      - huggingface-hub==0.36.0
      - numpy==2.2.6
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - safetensors==0.7.0
      - sympy==1.14.0
      - tokenizers==0.22.1
      - torch==2.9.1
      - torchvision==0.24.1
      - tqdm==4.67.1
      - transformers==4.57.3
      - typing-extensions==4.15.0
